import { dir } from 'i18next'
import { languages } from '../i18n/settings.js'
import '@fortawesome/fontawesome-free/css/all.min.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import { Footer } from './Components/Footer/Footer.jsx'
import { Navbar } from './Components/Navbar/navbar.jsx'
import Head from 'next/head.js'

export const metadata = {
  title: 'One supplier for your all industry needs',
  description: 'Generated by One Chemics Developer team',
}
export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

export default function RootLayout({
  children,
  params: {
    lng
  }
}) {
  return (
    <>
      <html lang={lng} dir={dir(lng)}>
        <Head>
          <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous" />
        </Head>
        {/* <head /> */}
        <body>
          <Navbar lng={lng} />
          {children}

          <Footer lng={lng} />
        </body>
      </html>
    </>
  )
}